# -*- coding: utf-8 -*-
"""PRAKALGO13ARJUNA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/187LnXgOeA11qjbm3Tc3bSS7VT9-zM50Y
"""

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @\n')
print('========== SOAL NO 1 ==========\n')
print ('========== kamis, 12 desember 2023 ==========\n')
nilai_siswa = [80, 75, 90, 85, 88]

rata_rata = sum(nilai_siswa) / len(nilai_siswa)
print("Rata-rata nilai siswa:", rata_rata)

nilai_diatas_80 = [nilai for nilai in nilai_siswa if nilai > 80]
print("Nilai siswa yang di atas 80:", nilai_diatas_80)

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @\n')
print('========== SOAL NO 2 ==========\n')
print ('========== kamis, 12 desember 2023 ==========\n')
def konversi(rupiah, dollar):
  hasil = rupiah / dollar
  return hasil

rupiah = int(input("masukan jumlah rupiah yang ingin kalian isi : "))
dollar = int(input('masukan jumlah kurs saat ini yaahh : '))

result = konversi(rupiah, dollar)

print(f'hasilnya sebanyak : $', result, 'ya teman teman <3 ')

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @\n')
print('========== SOAL NO 3 ==========\n')
print ('========== kamis, 12 desember 2023 ==========\n')


proyek_list = [
    {"nama": "Proyek A", "status": "Selesai", "estimasi_waktu": 10},
    {"nama": "Proyek B", "status": "Dalam Pengerjaan", "estimasi_waktu": 20},
    {"nama": "Proyek C", "status": "Dalam Pengerjaan", "estimasi_waktu": 15},
    {"nama": "Proyek D", "status": "Selesai", "estimasi_waktu": 8},
]

proyek_dalam_pengerjaan = [proyek for proyek in proyek_list if proyek["status"] == "Dalam Pengerjaan"]

def bubble_sort_proyek(proyek_list):
    n = len(proyek_list)
    for i in range(n - 1):
        for j in range(0, n - i - 1):
            if proyek_list[j]["estimasi_waktu"] > proyek_list[j + 1]["estimasi_waktu"]:
                proyek_list[j], proyek_list[j + 1] = proyek_list[j + 1], proyek_list[j]

print("Proyek yang masih dalam pengerjaan:")
for proyek in proyek_dalam_pengerjaan:
    print(f"Nama: {proyek['nama']}, Estimasi Waktu: {proyek['estimasi_waktu']} hari, Status: {proyek['status']}")

bubble_sort_proyek(proyek_dalam_pengerjaan)

print("\nProyek dalam pengerjaan yang diurutkan berdasarkan estimasi waktu:")
for proyek in proyek_dalam_pengerjaan:
    print(f"Nama: {proyek['nama']}, Estimasi Waktu: {proyek['estimasi_waktu']} hari, Status: {proyek['status']}")